name: octopus_vpn_core
description: "Client VPN indépendant Flutter V2Ray"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Utiliser la version officielle disponible
  flutter_v2ray: ^1.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config.json
    
