name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Permet de lancer le build manuellement d'un clic

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installe Java (requis par Android)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Installe Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # 4. Télécharge les dépendances
      - name: Install dependencies
        run: flutter pub get

      # 5. Compile l'APK en mode Release (APK universel)
      - name: Build APK
        run: flutter build apk --release --split-per-abi

      # 6. Sauvegarde l'APK pour que tu puisses le télécharger
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: octopus-vpn-apk
          path: build/app/outputs/flutter-apk/*.apk
          
